import * as Menu from 'Menu';
import * as Tag from 'Tag';
import * as CategoryMenu from 'CategoryMenu';
import * as WooCommerce from 'WooCommerce';

export const itemMenu: Menu.ItemMenu[] = [
  { title: 'Bakery', path: '#bakery' },
  { title: 'Fruit and vegetables', path: '#fruit_vegetables' },
  { title: 'Meat and fish', path: '#meat_fish' },
  { title: 'Drinks', path: '#drinks' },
  { title: 'Kitchen', path: '#kitchen' },
  { title: 'Special nutrition', path: '#Special_nutrition' },
  { title: 'Baby', path: '#baby' },
  { title: 'Pharmacy', path: '#pharmacy' },
];
export const productTags: Tag.ProductTag[] = [
  { name: 'Beans' },
  { name: 'Carrots' },
  { name: 'Apples' },
  { name: 'Garlic' },
  { name: 'Mushrooms' },
  { name: 'BeanTomatoes' },
  { name: 'Chilli peppers' },
  { name: 'Broccoli' },
  { name: 'Watermelons' },
  { name: 'Oranges' },
  { name: ' Meat' },
  { name: 'Seo tag' },
  { name: 'Fish' },
  { name: 'Fresh food' },
  { name: 'Lemons' },
  { name: 'Seo tag' },
];
export const footerLinks = [
  {
    title: 'Get in touch',
    links: ['About Us', 'Careers', 'Press Releases', 'Blog'],
  },
  {
    title: 'Connections',
    links: ['Facebook', 'Twitter', 'Instagram', 'Youtube', 'LinkedIn'],
  },
  {
    title: 'Earnings',
    links: ['Become an Affiliate', 'Advertise your product', 'Sell on Market'],
  },
  {
    title: 'Account',
    links: [
      'Your account',
      'Returns Centre',
      '100 % purchase protection',
      'Chat with us',
      'Help',
    ],
  },
];
export const categoryCard: CategoryMenu.CategoryCard[] = [
  {
    sub: 'Banner subfocus',
    title: 'Space for heading',
    textBtn: 'Read recepies',
  },
  {
    sub: 'Banner subfocus',
    title: 'Space for heading',
    textBtn: 'Read recepies',
  },
  {
    sub: 'Banner subfocus',
    title: 'Space for heading',
    textBtn: 'Read recepies',
  },
  {
    sub: 'Banner subfocus',
    title: 'Space for heading',
    textBtn: 'Read recepies',
  },
  {
    sub: 'Banner subfocus',
    title: 'Space for heading',
    textBtn: 'Read recepies',
  },
  {
    sub: 'Banner subfocus',
    title: 'Space for heading',
    textBtn: 'Read recepies',
  },
];
export const productList: WooCommerce.Product[] = [
  {
    id: 799,
    name: 'Product Title',
    slug: 'ship-your-idea-22',
    permalink: 'https://example.com/product/ship-your-idea-22/',
    date_created: '2017-03-23T17:03:12',
    date_created_gmt: '2017-03-23T20:03:12',
    date_modified: '2017-03-23T17:03:12',
    date_modified_gmt: '2017-03-23T20:03:12',
    type: 'variable',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description:
      'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.',
    short_description:
      'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    sku: '',
    price: '48.56',
    regular_price: '0.28',
    sale_price: '-36%',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    price_html: '',
    on_sale: false,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: false,
    stock_quantity: null,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '',
    dimensions: {
      length: '',
      width: '',
      height: '',
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '0.00',
    rating_count: 0,
    related_ids: [31, 22, 369, 414, 56],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [
      {
        id: 9,
        name: 'Clothing',
        slug: 'clothing',
      },
      {
        id: 14,
        name: 'T-shirts',
        slug: 't-shirts',
      },
    ],
    tags: [],
    images: [
      {
        id: 793,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 794,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 795,
        date_created: '2017-03-23T14:03:08',
        date_created_gmt: '2017-03-23T20:03:08',
        date_modified: '2017-03-23T14:03:08',
        date_modified_gmt: '2017-03-23T20:03:08',
        src:
          'https://www.cdc.gov/foodsafety/images/comms/food-Safety-Tips-small.jpg',
        name: '',
        alt: '',
      },
      {
        id: 796,
        date_created: '2017-03-23T14:03:09',
        date_created_gmt: '2017-03-23T20:03:09',
        date_modified: '2017-03-23T14:03:09',
        date_modified_gmt: '2017-03-23T20:03:09',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa2stfQ01420Zzw0EhOpPOo_juxVI3AEIuuw&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 797,
        date_created: '2017-03-23T14:03:10',
        date_created_gmt: '2017-03-23T20:03:10',
        date_modified: '2017-03-23T14:03:10',
        date_modified_gmt: '2017-03-23T20:03:10',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdHvSXXeaaOctfvhHXUM3-hzLOTeF32AKg_g&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 798,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 799,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 800,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 801,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 802,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
      {
        id: 803,
        date_created: '2017-03-23T14:03:11',
        date_created_gmt: '2017-03-23T20:03:11',
        date_modified: '2017-03-23T14:03:11',
        date_modified_gmt: '2017-03-23T20:03:11',
        src:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW7YUMcrmn1KENRXmBr7IQjxyB-rJqAOjnBA&usqp=CAU',
        name: '',
        alt: '',
      },
    ],
    attributes: [
      {
        id: 6,
        name: 'Color',
        position: 0,
        visible: false,
        variation: true,
        options: ['Black', 'Green'],
      },
      {
        id: 0,
        name: 'Size',
        position: 0,
        visible: true,
        variation: true,
        options: ['S', 'M'],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    _links: {
      self: [
        {
          href: 'https://example.com/wp-json/wc/v3/products/799',
        },
      ],
      collection: [
        {
          href: 'https://example.com/wp-json/wc/v3/products',
        },
      ],
    },
  },
];
